config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root :to => "categories#index", as: :authenticated_root
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    unauthenticated :user do
      root :to => "splash#index", as: :unauthenticated_root
    end
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  resources :categories, only: [:index, :new, :create, :show] do
    resources :payments, only: [:new, :create]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_payments, dependent: :destroy
  has_many :payments, through: :category_payments

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/category_payment.rb
class CategoryPayment < ApplicationRecord
  belongs_to :payment
  belongs_to :category
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_many :category_payments, dependent: :destroy
  has_many :categories, through: :category_payments

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :payments, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      flash[:notice] = 'Category successfully created.'
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @category = Category.find(params[:id])
    @payments = @category.payments.order(created_at: :desc)
    @sum = @payments.sum(:amount)
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @payment = Payment.new
  end

  def create
    @category = Category.find(params[:category_id])
    @payment = Payment.new(payment_params)
    @payment.user = current_user

    if @payment.save
      flash[:notice] = 'Transaction successfully created.'
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/index.html.erb
<div class="container">
  <h1 class="list blue">CATEGORIES</h1>

  <div class="sub-container">
    <% @categories.each do |category| %>
      <div class="list">
				<div class="item">
        	<%= image_tag(category.icon, alt: "Category icon") %>
				</div>
				<div class="item category">
        	<%= link_to category.name, category_path(category) %>
				</div>
				<div class="item amount">
        	$<%= category.payments.sum(:amount) %>
				</div>
      </div>
    <% end %>
  </div>
	<div>
		<div class="add-new">
  		<%= link_to "ADD A NEW CATEGORY", new_category_path %>
		</div>	
	</div>
</div>

app/views/categories/new.html.erb
<div class="container">
	<div class="back">
		<%= link_to "<", categories_path %>
	</div>

	<h2 class="list blue">NEW CATEGORY</h2>

  <div class="sub-container">
		<%= form_with model: @category do |form| %>
    	<div>
      	<%= form.label :name %><br>
      	<%= form.text_field :name, placeholder: "Category name", class: "field", required: true %>
    	</div>
    	<div>
      	<%= form.label :icon %><br>
      	<%= form.text_field :icon, placeholder: "Icon link", class: "field", required: true %>
    	</div>
			<div class="add-item">
    		<%= form.submit "ADD CATEGORY", class: "add" %>
			</div>
  	<% end %>
	</div>
</div>

app/views/categories/show.html.erb
<div class="container">

  <div class="back">
    <%= link_to "<", categories_path %>
  </div>

  <h2 class="list blue">TRANSACTIONS</h2>

  <div class="list">
    <h3><%= @category.name %></h3>
    <p class="amount">$<%= @sum %></p>
  </div>

  <div class="sub-container">
    <% @payments.each do |payment| %>
      <div class="list">
        <p class="category"><%= payment.name %></p>
        <p class="amount">$<%= payment.amount %></p>
      </div>
    <% end %>
  </div>

  <div class="add-new">
    <%= link_to "ADD A NEW TRANSACTION", new_category_payment_path(@category) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetAppRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
  <nav>
    <p>Hello <%= current_user.name %></p>
    <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
  </nav>
<% end %>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/payments/new.html.erb
<div class="container">
  <div class="back">
    <%= link_to "<", category_path(@category) %>
  </div>

	<h2 class="list blue">NEW TRANSACTION</h2>
    
  <div class="sub-container">
    <%= form_with model: @payment, url: category_payments_path(@category) do |form| %>
      <div>
        <%= form.label :name %><br>
        <%= form.text_field :name, class: "field", required: true %>
      </div>
      <div>
        <%= form.label :amount %><br>
        <%= form.number_field :amount, class: "field", required: true %>
      </div>
      <div>
        <%= form.label "Categories" %><br>
        <%= form.collection_select(:category_ids, current_user.categories, :id, :name, {}, { multiple: true, class: "field", required: true }) %>
      </div>
      <div class="add-item">
        <%= form.submit "ADD TRANSACTION", class: "add" %>
      </div>
    <% end %>
  </div>
</div>

app/views/splash/index.html.erb
<div class="splash">
	<h1>Budget Navigator</h1>
  <div class="sign-in">
    <%= link_to "Sign in", new_user_session_path %>
  </div>
  <div class="sign-up">
    <%= link_to "Sign up", new_user_registration_path %>
  </div>
</div>